layout_spectrum: 0.9569983
name: "Joshua's Pie Mobile Wood Fired Pizza"
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
color:
  brandStrength: 0.1006427
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
  brandColors:
    - '#040204'
    - '#E9EAE7'
    - '#9A0117'
    - '#77777F'
    - '#C6A3A3'
typography_spectrum: 0.0455312
