layout_spectrum: 0.9569983
color:
  saturation: 0
  brandStrength: 0.1006427
  lightness: 0
  rhythmicContrast: 1
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.0455312
name: "Joshua's Pie Mobile Wood Fired Pizza"
